# Generated by Django 6.0.1 on 2026-01-11 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('events', models.JSONField(blank=True, default=list)),
                ('people', models.ManyToManyField(blank=True, related_name='dayblocks', to='core.people')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('camera', models.CharField(choices=[('cam1', 'Cam 1'), ('cam2', 'Cam 2'), ('cam3', 'Cam 3'), ('cam4', 'Cam 4')], max_length=16)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('video', models.FileField(upload_to='footage/%Y/%m/%d/')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dayblock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.dayblock')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_id', models.CharField(max_length=64, unique=True)),
                ('week_number', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('summary', models.TextField(blank=True, default='')),
                ('days', models.ManyToManyField(blank=True, related_name='weeks', to='core.dayblock')),
            ],
        ),
        migrations.AddIndex(
            model_name='dayblock',
            index=models.Index(fields=['date', 'location'], name='core_dayblo_date_ce184c_idx'),
        ),
        migrations.AddConstraint(
            model_name='dayblock',
            constraint=models.UniqueConstraint(fields=('date', 'location'), name='uniq_dayblock_date_location'),
        ),
        migrations.AddIndex(
            model_name='individualvideo',
            index=models.Index(fields=['camera'], name='core_indivi_camera_e661c2_idx'),
        ),
        migrations.AddIndex(
            model_name='individualvideo',
            index=models.Index(fields=['created_at'], name='core_indivi_created_7d6046_idx'),
        ),
        migrations.AddIndex(
            model_name='individualvideo',
            index=models.Index(fields=['dayblock', 'camera'], name='core_indivi_daybloc_6333b5_idx'),
        ),
    ]
