# Generated by Django 6.0.1 on 2026-01-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dayblock_individualvideo_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='face',
            field=models.FileField(upload_to='faces/'),
        ),
    ]
