# Generated by Django 6.0.1 on 2026-01-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_people_face'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='face',
        ),
        migrations.AddField(
            model_name='people',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
        migrations.AddField(
            model_name='people',
            name='scan_video',
            field=models.FileField(blank=True, null=True, upload_to='people_scans/'),
        ),
    ]
