# Generated by Django 6.0.1 on 2026-01-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_people_face_people_face_image_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dayblock',
            name='core_dayblo_date_ce184c_idx',
        ),
    ]
