# Generated by Django 6.0.1 on 2026-01-11 07:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_dayblock_core_dayblo_date_ce184c_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualvideo',
            name='video',
            field=models.FileField(upload_to=core.models.footage_upload_path),
        ),
    ]
